name: Test

on:
  push:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: [ 'CS' ]
        racket-version: [ 'current', 'stable' ]
    steps:
    - uses: actions/checkout@master
    - name: Cache installed packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.racket
        key: ${{ runner.os }}-primes
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64' # (x64 or x86), ignored on Linux
        distribution: 'minimal'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - run: raco pkg install --auto
    - run: make test
